# Generated by Django 5.0.4 on 2024-04-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_email', models.EmailField(max_length=100, unique=True)),
                ('artist_phone', models.CharField(max_length=10)),
                ('artist_pass', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
