# Generated by Django 5.0.4 on 2024-04-10 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_artists_delete_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=30)),
                ('art_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art_category', models.CharField(max_length=50)),
                ('art_quantity', models.IntegerField(verbose_name=10)),
                ('art_description', models.TextField()),
                ('art_image', models.ImageField(upload_to='art_images')),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.artists')),
            ],
        ),
    ]
