# Generated by Django 5.0.4 on 2024-04-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_art_art_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_username', models.CharField(max_length=20)),
                ('artist_password', models.CharField(max_length=20)),
                ('Artists_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_username', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=50)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.art')),
            ],
        ),
    ]
