# Generated by Django 5.0.4 on 2024-04-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_category_artist_login_customer_login_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.art')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.CharField(max_length=100)),
                ('payment_info', models.CharField(max_length=255)),
                ('payment_tra_id', models.CharField(max_length=100)),
                ('paymentApiStatus', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.art')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.art')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.customer')),
            ],
        ),
    ]
