# Generated by Django 5.0.4 on 2024-04-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_rename_artists_artist_rename_category_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
